### ISSUE TITLE
i.landsat.trim errors

### ISSUE THREAD

**Issue by ljbade** [amuriy/GRASS-scripts#1]
When I try to use your i.landsat.trim script I get these errors:

(Tue Sep 11 17:34:38 2012)  
i.landsat.trim input=LT50720882005312HOA02_B1@PERMANENT output_prefix=trim  
=== Processing raster: LT50720882005312HOA02_B1@PERMANENT ===
Creating raster mask ...
Creating raster buffer with distance <300> ...
Growing raster and cut mask ...
Vectorize raster mask ...
**ERROR: Vector map <I_LANDSAT_TRIM_mask> not found**
Extract main area from mask ...
**ERROR: Vector map <I_LANDSAT_TRIM_lcats> not found in the current mapset**
**ERROR: Vector map <I_LANDSAT_TRIM_lcats> not found in the current mapset**
Generalizing vectors ...
Rasterizing vector mask ...
Write trimmed raster to LT50720882005312HOA02_B1@PERMANENT.trim ...
C:/OSGeo4W/apps/grass/grass-6.4.2/scripts/i.landsat.trim:
**line 210: r.mask: command not found**
**syntax error, unexpected '@', expecting '='**
**Parse error**
C:/OSGeo4W/apps/grass/grass-6.4.2/scripts/i.landsat.trim:
## **line 212: r.mask: command not found**

(Tue Sep 11 17:34:48 2012) Command finished (9 sec)                             

I am using GRASS 6.4.2 in OSGEO4W.

**Comment by amuriy** [comment]
Hello Leith.

Maybe there is no <r.mask> script in GRASS 6.4.2 (OSGEO4W), it's a Unix
shell script. I can't fix that. Module i.landsat.trim> was tested only at
Linux systems.

One of solutions would be rewriting script in Python for GRASS 7.0. I was
just thinking about it.

2012/9/11 Leith Bade notifications@github.com

**Comment by ljbade** [comment]
OK, I managed to get it working on Linux.

However I notice that it does not handle tiles that contain ocean. It trims
the sea off the image, is it possible to change this so it only trims to
the edge of scanlines?

Thanks,
Leith Bade
leith@leithalweapon.geek.nz

**Comment by amuriy** [comment]
Thanks for testing, Leith.

I'll try to test script with ocean/sea images, but, of course, it would be
better to see your data on which the errors occurred. Could you show me the
input and output images?

2012/9/12 Leith Bade notifications@github.com

> OK, I managed to get it working on Linux.
> 
> However I notice that it does not handle tiles that contain ocean. It
> trims
> the sea off the image, is it possible to change this so it only trims to
> the edge of scanlines?
> 
> Thanks,
> Leith Bade
> leith@leithalweapon.geek.nz

**Comment by ljbade** [comment]
Hi Alex,

Here is an screen show of the before and after trim (ignore
the contrast difference):
[image: Inline images 1]
[image: Inline images 2]
As you can see it trims right up to the coastline, rather than the edge of
the Landsat image.

This scene is LT50720882005312HOA02 and the band is band 3.

Thanks,
Leith Bade
leith@leithalweapon.geek.nz

**Comment by amuriy** [comment]
Hi Leith.

I can't see images in your mail, but I already downloaded scene
LT50720882005312HOA02 and will test my module. If will be some results,
I'll post to you.

2012/9/14 Leith Bade notifications@github.com

> Hi Alex,
> 
> Here is an screen show of the before and after trim (ignore
> the contrast difference):
> [image: Inline images 1]
> [image: Inline images 2]
> As you can see it trims right up to the coastline, rather than the edge of
> the Landsat image.
> 
> This scene is LT50720882005312HOA02 and the band is band 3.
> 
> Thanks,
> Leith Bade
> leith@leithalweapon.geek.nz
>
